[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
solc = "0.8.20"
bytecode_hash = "none"
optimizer_runs = 1000000

[dependencies]
forge-std = "1.9.5"
solmate = "6.8.0"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
